---
title: "SOC sequestration potential"
author: "Jacob Spertus"
date: "3/08/2023"
header-includes:
  -\usepackage{amsmath}
  -\usepackage{amsfonts}
output:
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(maps)
library(splines)
library(xtable)
library(hettx)
library(latex2exp)
```

# Plot potential trajectories
```{r}
time <- seq(0, 10, length.out = 100)
response_1 <- log(1 + 2*time)
response_2 <- 2 * (pnorm(0.5 * time) - 0.5)
response_3 <- -0.1 * time
response_4 <- time - (0.3 * (time))^2

pt_data <- data.frame(
  "x" = rep(time, 4), 
  "y" = c(response_1, response_2, response_3, response_4), 
  "scenario" = rep(c("Concave growth", "New equilibrium", "Locally linear loss", "Reversal"), each = length(time)))

pt_plot <- ggplot(pt_data, aes(x = x, y = y, color = scenario)) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_line(size = 1.5) + 
  theme_bw() +
  ylim(-1,10) +
  scale_colour_manual(values = c("steelblue", "firebrick", "forestgreen", "darkorange3")) +
  theme(
    text = element_text(linewidth = 18), 
    axis.text.y = element_blank(), 
    axis.ticks.y = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    legend.text = element_text(linewidth = 14),
    legend.title = element_blank(),
    panel.border = element_blank(),
    legend.key.width = unit(1, "cm")) +
  labs(title = "Potential trajectories", x = "Time", y = "SOC change")

pt_plot
```

# Observed trajectory
```{r}
time <- seq(0, 10, length.out = 100)
response_1 <- log(1 + 2*time)
response_2 <- 2 * (pnorm(0.5 * time) - 0.5)
response_3 <- -0.1 * time
response_4 <- time - (0.3 * (time))^2

ot_data <- data.frame(
  "x" = rep(time, 4), 
  "y" = c(response_1, response_2, response_3, response_4), 
  "scenario" = rep(c("Concave growth", "New equilibrium", "Locally linear loss", "Reversal"), each = length(time)),
  "trajectory" = factor(rep(c("Realized", "Counterfactual", "Counterfactual", "Counterfactual"), each = length(time)), levels = c("Realized", "Counterfactual"))) 

ot_plot <- ggplot(ot_data, aes(x = x, y = y, color = scenario, linetype = trajectory)) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_line(linewidth = 1.5) + 
  theme_bw() +
  ylim(-1,10) +
  scale_colour_manual(values = c("steelblue", "firebrick", "forestgreen", "darkorange3")) +
  theme(
    text = element_text(size = 18), 
    axis.text.y = element_blank(), 
    axis.ticks.y = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    legend.text = element_text(size = 14),
    legend.title = element_blank(),
    panel.border = element_blank(),
    legend.key.width = unit(1, "cm")) +
  labs(title = "Trajectories", x = "Time", y = "SOC change")

ot_plot
```

# Saturation as decreasing CATE and as Dose-Response

```{r}
#dose response
dose <- seq(0, 10, length.out = 100)
response_complete_saturation <- 6 * pnorm(dose/2) - 3
response_partial_saturation <- log(1 + 10*dose)
response_no_saturation <- dose
response_convex <- (dose/2)^2 /4
dr_data <- data.frame(
  "hypothesis" = "Dose-response",
  "x" = rep(dose, 4), 
  "y" = c(response_complete_saturation, response_partial_saturation, response_no_saturation, response_convex), 
  "scenario" = rep(c("Saturation", "Diminishing returns", "Linear storage", "Increasing returns"), each = length(dose)))

#conditional average treatment effect
baseline <- seq(0,5, length.out = 100)
CATE_moderation <- exp(-baseline)
CATE_nomoderation <- rep(0.5, length(baseline))
cate_data <- data.frame(
  "hypothesis" = "Saturation-moderation",
  "x" = rep(baseline, 2),
  "y" = c(CATE_moderation, CATE_nomoderation),
  "scenario" = rep(c("Complete saturation", "No Saturation"), each = length(baseline)))

combined_data <- bind_rows(dr_data, cate_data)

#dose response plot
dr_plot <- ggplot(dr_data, aes(x = x, y = y, color = scenario)) +
  geom_line(size = 1.5) + 
  geom_hline(yintercept = 3, linetype = 'dashed') +
  theme_bw() +
  scale_colour_manual(values = c("darkorange3", "steelblue", "forestgreen", "firebrick")) +
  theme(
    text = element_text(size = 18), 
    axis.text = element_blank(), 
    axis.ticks = element_blank(),
    legend.text = element_text(size = 14),
    legend.title = element_blank(),
    panel.border = element_blank(),
    legend.key.width = unit(1, "cm")) +
  labs(x = "Carbon inputs", y = "SOC change at equilibrium")

#CATE plot
cate_plot <- ggplot(cate_data, aes(x = x, y = y, color = scenario)) +
  geom_line(size = 1.5) + 
  theme_bw() +
  scale_colour_manual(values = c("steelblue","darkorange3")) +
  theme(
    text = element_text(size = 18), 
    axis.text = element_blank(), 
    axis.ticks = element_blank(),
    legend.text = element_text(size = 14),
    legend.title = element_blank(),
    panel.border = element_blank(),
    legend.key.width = unit(1, "cm")) +
  labs(title = "(a) Moderation", x = "Baseline SOC", y = "SOC sequestered")
```

```{r}
dr_plot
```

```{r}
cate_plot
```

# NRCS Study

The following data were collected by the Silver Lab from 7 paired treatment-control sites around California. Baseline topsoil samples were gathered and treatment was applied in 2016. The last top soil samples were gathered in 2019.

```{r read nrcs data}
#the data was edited from the file Whendee sent in Excel: spaces in site names were removed
#also standardized to "TomKat" 
nrcs_data <- read_csv("~/Dropbox/Carbon and Land Use/Data/NRCS 7site 2016-2019 edited.csv") %>%
  rename(samples = "Samples (same as 2018 & 2019)", TN = "%N", TC = "%C") %>%
  mutate(samples = gsub("cm ", "", samples)) %>%
  separate_wider_delim(samples, delim = " ", names = c("sample", "site", "depth_cm", "year")) %>%
  separate_wider_position(sample, c(treatment = 1, sample = 1)) %>%
  #mutate(site = gsub("BethelIsand", "BethelIsland", site)) %>% #there's a typo in one site name
  #filter(year %in% c(2016, 2019)) %>%
  filter(depth_cm == "0-10") %>%
  filter(site != "BethelIsland")
```




## NRCS Simulation

```{r extract parameters from NRCS data}
nrcs_summaries <- nrcs_data %>% 
  group_by(year, treatment) %>%
  summarize(mean_TC = mean(TC), sd_TC = sd(TC))

#helper function
stdize <- function(x){(x-mean(x))/sd(x)}
  
  
##assay variability

##baseline level means and spatial heterogeneities pooled across trt and ctl
#baseline mean
baseline_avg <- nrcs_data %>% 
  filter(year == 2016, depth_cm == "0-10") %>% 
  summarize(mean_TC = mean(TC)) %>% 
  pull(mean_TC)
#baseline within plot spatial heterogeneity
baseline_wp_var <- nrcs_data %>%
  filter(year == 2016, depth_cm == "0-10") %>% 
  group_by(site) %>% #note that Koopman is an outlier, with almost an order of magnitude higher SD
  summarize(var_TC = var(TC)) %>%
  ungroup() %>%
  summarize(wp_var = mean(var_TC)) %>%
  pull(wp_var)
#baseline across plot spatial heterogeneity
baseline_ap_var <- nrcs_data %>%
  filter(year == 2016, depth_cm == "0-10") %>% 
  group_by(site) %>% 
  summarize(mean_TC = mean(TC)) %>%
  ungroup() %>%
  summarize(ap_var = var(mean_TC)) %>%
  pull(ap_var)
## change from baseline to followup for control plots
#compute mean, within plot and across
change_ctl <- nrcs_data %>% 
  filter(year %in% c(2016, 2019), depth_cm == "0-10", treatment == "C") %>% 
  select(-TN) %>%
  pivot_wider(names_from = "year", values_from = "TC", names_prefix = "TC_") %>%
  mutate(diff = TC_2019 - TC_2016) %>%
  group_by(site) %>%
  summarize(mean_diff = mean(diff), var_diff = var(diff)) %>% 
  ungroup() %>%
  summarize(mean_change = mean(mean_diff), wp_var_change = mean(var_diff), ap_var_change = var(mean_diff))
mean_change_ctl <- change_ctl$mean_change
wp_var_change_ctl <- change_ctl$wp_var_change
ap_var_change_ctl <- change_ctl$ap_var_change

#estimate a treatment effect from the study using difference in differences
treatment_effect <- nrcs_data %>% 
  select(-TN) %>% 
  group_by(treatment, site, year) %>%
  summarize(TC = mean(TC)) %>%
  pivot_wider(names_from = "year", values_from = "TC", names_prefix = "TC_") %>%
  mutate(diff = TC_2019 - TC_2016) %>%
  select(treatment, site, diff) %>%
  pivot_wider(names_from = treatment, values_from = diff, names_prefix = "diff_") %>%
  mutate(DiD = diff_T - diff_C) %>%
  ungroup() %>%
  summarize(mean_DiD = mean(DiD), se_DiD = sd(DiD) / sqrt(n()), n = n()) %>%
  mutate(
    lower_ci = mean_DiD + qt(0.05, n-1) * se_DiD, 
    upper_ci = mean_DiD - qt(0.05, n-1) * se_DiD) %>%
  pull(mean_DiD)
```


```{r set up parameters for NRCS simulations}
N = 5000 #population size 
assay_variability <- 0 #assume lab work is error-free for now
#effect size as a function of the baseline spatial heterogeneity
effect_size <- c(0, 0.05, 0.1, 0.3) #null, small, medium, large effect (5%, 10%, 30%)
ate <- round(effect_size / sqrt(baseline_ap_var), 2)
moderator_effect <- -c(0, 0.1, 0.5) #range of moderator effects
idiosyncratic_teh <- c(0, 0.1) #this is idiosyncratic variation in the treatment effects
measurement_noise <- round(c(
                         assay_variability + baseline_wp_var/5, 
                         assay_variability + baseline_wp_var/30, 
                         assay_variability + baseline_wp_var/100,
                         0), 
                       2) #variability due to sampling / within-plot spatial heterogeneity. n = 5,30,100 samples per plot
n <- c(10, 100, 1000) #size of experiment

nrcs_parameters <- expand.grid(
  ate = ate, 
  moderator_effect = moderator_effect, 
  idiosyncratic_teh = idiosyncratic_teh, 
  measurement_noise = measurement_noise, 
  n = n)
```



```{r run NRCS simulations}
all_results <- list()
for(i in 1:nrow(nrcs_parameters)){
  param_list_i <- list(
    baseline_avg = baseline_avg,
    baseline_ap_var = baseline_ap_var,
    mean_var_change_ctl = mean_var_change_ctl,
    ap_var_change_ctl = ap_var_change_ctl,
    ate = nrcs_parameters$ate[i], 
    moderator_effect = nrcs_parameters$moderator_effect[i],
    idiosyncratic_teh = nrcs_parameters$idiosyncratic_teh[i],
    measurement_noise = nrcs_parameters$measurement_noise[i], 
    n = nrcs_parameters$n[i]
  )
  all_results[[i]] <- run_simulation(param_list_i, num_sims = 200)
}
results_frame <- all_results %>% 
  reduce(bind_rows) %>% 
  as_tibble() 
```

```{r comparing ATE estimators}
#breakdown by moderator effect
pate_estimates_spme <- results_frame %>% 
  select(spate, spme, n, teh, measurementnoise, starts_with("diffmeans"), starts_with("diffdiffs"), starts_with("olsest")) %>%
  pivot_longer(cols = contains("_")) %>%
  separate_wider_delim(name, "_", names = c("estimator", "criterion")) %>%
  group_by(spme, n, estimator, criterion) %>% #model-averaging over spate, teh, measurementnoise
  summarize(value = median(value)) 
```



```{r full PATE results}
pate_results_table_full <- results_frame %>%
  select(n, spate, spme, measurementnoise, teh, diffmeans_rmse, diffdiffs_rmse, olsest_rmse, diffmeans_coverage, diffdiffs_coverage, olsest_coverage, diffmeans_ciwidth, diffdiffs_ciwidth, olsest_ciwidth) %>%
  pivot_longer(cols = contains("_")) %>%
  separate_wider_delim(name, "_", names = c("estimator", "criterion")) %>%
  pivot_wider(names_from = criterion, values_from = value) %>%
  filter(spate == 0, teh == 0) %>%
  select(-spate) %>%
  arrange(spme, measurementnoise)
#print(xtable(pate_results_table_full), include.rownames = FALSE)
```


```{r table of PATE results averaged over populations}
#empirical bias is essentially 0 and doesn't differ across estimators, don't present it
#model averaging: average results across spate, spme, measurement noise, and teh
pate_results_table_avg <- results_frame %>%
  select(n, spate, spme, measurementnoise, teh, diffmeans_rmse, diffdiffs_rmse, olsest_rmse, diffmeans_coverage, diffdiffs_coverage, olsest_coverage, diffmeans_ciwidth, diffdiffs_ciwidth, olsest_ciwidth, diffmeans_bias, diffdiffs_bias, olsest_bias) %>%
  pivot_longer(cols = contains("_")) %>%
  separate_wider_delim(name, "_", names = c("estimator", "criterion")) %>%
  group_by(n, estimator, criterion) %>%
  summarize(value = mean(value)) %>%
  ungroup() %>%
  pivot_wider(names_from = criterion, values_from = value)

#print(xtable(pate_results_table_avg), include.rownames = FALSE)
```

```{r moderator estimates}
mod_est_results <- results_frame %>% 
  group_by(n, measurementnoise) %>%
  summarize(
    modest_bias = mean(modest_bias), 
    modest_rmse = mean(modest_rmse), 
    modest_coverage = mean(modest_coverage), 
    modest_ciwidth = mean(modest_ciwidth),
    naive_bias = mean(naive_modest_bias), 
    naive_rmse = mean(naive_modest_rmse), 
    naive_coverage = mean(naive_modest_coverage), 
    naive_ciwidth = mean(naive_modest_ciwidth)) %>%
  ungroup() %>%
  pivot_longer(cols = -c(n, measurementnoise)) %>%
  separate_wider_delim(name, "_", names = c("estimator", "measure")) %>%
  mutate(plot_sample_size = factor(case_match(measurementnoise, 0 ~ "Infinite", 0.01 ~ "100", 0.04 ~ "30", 0.21 ~ "5"), levels = c("Infinite", "100", "30", "5"))) %>%
  mutate(Measure = case_match(measure, "bias" ~ "Bias", "rmse" ~ "RMSE", "coverage" ~ "95% CI coverage", "ciwidth" ~ "CI Width")) %>%
  mutate(Estimator = case_match(estimator, "modest" ~ "Causal Regression", "naive" ~ "Naive Regression"))


ggplot(mod_est_results %>% filter(measure %in% c("coverage")), aes(x = as_factor(n),  y = value, color = plot_sample_size)) +
  geom_point(size = 3) +
  geom_hline(yintercept = .95, linetype = 'dashed') +
  scale_y_continuous(limits = c(0,1), labels = scales::percent) +
  facet_grid(Estimator ~ ., scales = "free") +
  labs(
    x = "Number of plots in study (n)",
    y = "True coverage of 95% confidence intervals",
    color = "Samples per plot"
  ) +
  theme_bw() +
  theme(text = element_text(size = 24)) 

ggplot(mod_est_results %>% filter(measure %in% c("bias")), aes(x = as_factor(n),  y = value, color = plot_sample_size)) +
  geom_point(size = 2) +
  geom_hline(yintercept = 0, linetype = 'dashed') +
  facet_grid(Estimator ~ Measure) +
  labs(
    x = "Number of plots in study (n)",
    y = "Value",
    color = "Samples per plot"
  ) +
  theme_bw() +
  theme(text = element_text(size = 24)) 
```


```{r pate estimation power}
num_sims <- 500
samples_per_plot <- c(5, 100)
measurement_noise <- round(c(assay_variability + baseline_wp_var/samples_per_plot), 2) 
n <- c(14, 140)
simulation_parameters <- expand.grid(
  ate = seq(0, 1, by = .05), 
  moderator_effect = c(0, -0.5), 
  idiosyncratic_teh = 0, 
  measurement_noise = measurement_noise, 
  n = n)

all_results_power <- list()
for(i in 1:nrow(simulation_parameters)){
  all_results_power[[i]] <- run_simulation(
    simulation_parameters$ate[i], 
    simulation_parameters$moderator_effect[i],  
    simulation_parameters$idiosyncratic_teh[i], 
    simulation_parameters$measurement_noise[i], 
    simulation_parameters$n[i])
}
results_frame_power <- all_results_power %>% 
  reduce(bind_rows) %>% 
  as_tibble() 
```

```{r}
results_frame_power_long <- results_frame_power %>%
  select(n, spate, spme, measurementnoise, diffmeans_power, diffdiffs_power, olsest_power) %>%
  pivot_longer(cols = contains("_"), names_to = "estimator", values_to = "power") %>%
  mutate(plot_sample_size = factor(case_match(measurementnoise, 0 ~ "Infinite", 0.01 ~ "100", 0.04 ~ "30", 0.21 ~ "5"), levels = c("Infinite", "100", "30", "5"))) %>%
  mutate(relative_change = spate / baseline_avg) %>%
  filter(n != 1400) %>%
  filter(spme == -0.5) %>%
  #filter(estimator != "diffdiffs_power") %>%
  mutate(n_long = paste("n =", n)) %>%
  mutate(estimator_long = case_match(estimator, "diffmeans_power" ~ "DiM", "diffdiffs_power" ~ "DiD", "olsest_power" ~ "OLS"))

ggplot(results_frame_power_long, aes(x = relative_change, y = power, color = estimator_long, linetype = plot_sample_size)) +
  geom_line(size = 1.8) +
  facet_grid(n_long ~ .) +
  scale_y_continuous(labels = scales::percent) +
  scale_x_continuous(labels = scales::percent) +
  labs(
    x = "PATE size (%SOC relative to baseline)",
    y = "Power",
    linetype = "Samples per plot",
    color = "Estimator") +
  theme_bw() +
  theme(
    text = element_text(size = 18),
    legend.key.width = unit(2, "cm"))
```


```{r pate simulations over n}
samples_per_plot <- c(5, 30, 100)
measurement_noise <- round(c(assay_variability + baseline_wp_var/samples_per_plot), 2) 
n <- seq(10,200, by = 4)
simulation_parameters <- expand.grid(
  ate = 0, 
  moderator_effect = c(0, -0.5), 
  idiosyncratic_teh = 0, 
  measurement_noise = measurement_noise, 
  n = n)

all_results_n <- list()
for(i in 1:nrow(simulation_parameters)){
  all_results_n[[i]] <- run_simulation(
    simulation_parameters$ate[i], 
    simulation_parameters$moderator_effect[i],  
    simulation_parameters$idiosyncratic_teh[i], 
    simulation_parameters$measurement_noise[i], 
    simulation_parameters$n[i])
}
results_frame_n <- all_results_n %>% 
  reduce(bind_rows) %>% 
  as_tibble() 
```

```{r plot PATE properties as a function of n}
results_frame_n_long <- results_frame_n %>%
  select(n, spme, measurementnoise, diffmeans_rmse, diffdiffs_rmse, olsest_rmse, diffmeans_coverage, diffdiffs_coverage, olsest_coverage, diffmeans_ciwidth, diffdiffs_ciwidth, olsest_ciwidth) %>%
  pivot_longer(cols = contains("_")) %>%
  separate_wider_delim(name, "_", names = c("estimator", "criterion")) %>%
  mutate(samples_per_plot = paste("Samples per plot = ", samples_per_plot[match(measurementnoise, measurement_noise)])) %>%
  mutate(estimator = case_match(estimator, "diffdiffs" ~ "DiD", "diffmeans" ~ "DiM", "olsest" ~ "OLS")) 

ggplot(results_frame_n_long %>% filter(criterion == "ciwidth"), aes(x = n, y = value, color = estimator)) +
  geom_line(size = 1.1) +
  facet_grid(spme ~ samples_per_plot) +
  theme_bw() + 
  ylab("Average confidence interval width (TC%)") +
  xlab("Study size (n)") +
  coord_cartesian(ylim = c(0,1)) +
  labs(colour = "Estimator") +
  theme(
    text = element_text(size = 18), 
    axis.text = element_text(size = 14),
    legend.key.width = unit(2, "cm"),
    legend.text = element_text(size = 14))
```



```{r comparing policy estimates}
policy_loss_frame <- results_frame %>%
  select(spate, spme, oracle_mean, avg_optimal_policy_estimate, avg_restricted_optimal_policy_estimate) %>%
  pivot_longer(
    cols = c("avg_optimal_policy_estimate", "avg_restricted_optimal_policy_estimate"), 
    names_to = "estimate",
    values_to = "value") %>%
  mutate(policy_loss = oracle_mean - value) %>%
  mutate(fpme = as_factor(round(spme, 2)))


model_avg_policy_loss <- policy_loss_frame %>%
  group_by(estimate) %>% 
  summarize(oracle_mean = mean(oracle_mean), value = mean(value), policy_loss = mean(policy_loss))

model_avg_policy_loss <- policy_loss_frame %>%
  group_by(estimate, spme) %>% 
  summarize(oracle_mean = mean(oracle_mean), value = mean(value), policy_loss = mean(policy_loss))


ggplot(policy_loss_frame, aes(policy_loss, fill = estimate)) +
  geom_histogram(position = "identity", alpha = 0.75) +
  theme_bw() +
  facet_grid(. ~ spme)

ggplot(results_frame, aes(x = avg_restricted_optimal_policy_estimate, y = avg_optimal_policy_estimate, colour = fpme)) +
  geom_point() + 
  geom_abline(yintercept = 0, slope = 1, linetype = 'dashed')
```











